<a href="https://colab.research.google.com/github/abhinav371/python_numpy/blob/numpy-1/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [3]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b=np.array([[1.0,9.0,8.0],[7.0,18.0,45.0]])
print(b)

[[ 1.  9.  8.]
 [ 7. 18. 45.]]


In [10]:
#dimension
b.ndim

2

In [12]:
#type
b.dtype

dtype('float64')

In [14]:
#size
b.size

6

In [16]:
#bytes
b.nbytes

48